-- Auto-generated from src/lib/translations.ts
-- Run in Supabase SQL editor


INSERT INTO public.content_registry (key, section, label, content_type, description, sort_order)
VALUES
('clients.subtitle', 'clients', 'Clients / Subtitle', 'text', 'Clients / Subtitle', 0),
('clients.title', 'clients', 'Clients / Title', 'text', 'Clients / Title', 1),
('contact.address', 'contact', 'Contact / Address', 'text', 'Contact / Address', 2),
('contact.email', 'contact', 'Contact / Email', 'text', 'Contact / Email', 3),
('contact.phone', 'contact', 'Contact / Phone', 'text', 'Contact / Phone', 4),
('contact.subtitle', 'contact', 'Contact / Subtitle', 'text', 'Contact / Subtitle', 5),
('contact.title', 'contact', 'Contact / Title', 'text', 'Contact / Title', 6),
('contact.workingHours', 'contact', 'Contact / Working Hours', 'text', 'Contact / Working Hours', 7),
('countries.connectionsTitle', 'countries', 'Countries / Connections Title', 'text', 'Countries / Connections Title', 8),
('countries.currentOffice', 'countries', 'Countries / Current Office', 'text', 'Countries / Current Office', 9),
('countries.description', 'countries', 'Countries / Description', 'textarea', 'Countries / Description', 10),
('countries.officeInfo.Austria.address', 'countries', 'Countries / Office Info / Austria / Address', 'text', 'Countries / Office Info / Austria / Address', 11),
('countries.officeInfo.Austria.city', 'countries', 'Countries / Office Info / Austria / City', 'text', 'Countries / Office Info / Austria / City', 12),
('countries.officeInfo.Austria.phone', 'countries', 'Countries / Office Info / Austria / Phone', 'text', 'Countries / Office Info / Austria / Phone', 13),
('countries.officeInfo.Czech Republic.address', 'countries', 'Countries / Office Info / Czech Republic / Address', 'text', 'Countries / Office Info / Czech Republic / Address', 14),
('countries.officeInfo.Czech Republic.city', 'countries', 'Countries / Office Info / Czech Republic / City', 'text', 'Countries / Office Info / Czech Republic / City', 15),
('countries.officeInfo.Czech Republic.phone', 'countries', 'Countries / Office Info / Czech Republic / Phone', 'text', 'Countries / Office Info / Czech Republic / Phone', 16),
('countries.officeInfo.Slovakia.address', 'countries', 'Countries / Office Info / Slovakia / Address', 'text', 'Countries / Office Info / Slovakia / Address', 17),
('countries.officeInfo.Slovakia.city', 'countries', 'Countries / Office Info / Slovakia / City', 'text', 'Countries / Office Info / Slovakia / City', 18),
('countries.officeInfo.Slovakia.phone', 'countries', 'Countries / Office Info / Slovakia / Phone', 'text', 'Countries / Office Info / Slovakia / Phone', 19),
('countries.subtitle', 'countries', 'Countries / Subtitle', 'text', 'Countries / Subtitle', 20),
('countries.title', 'countries', 'Countries / Title', 'text', 'Countries / Title', 21),
('footer.copyright', 'footer', 'Footer / Copyright', 'text', 'Footer / Copyright', 22),
('footer.newsletterCta', 'footer', 'Footer / Newsletter Cta', 'text', 'Footer / Newsletter Cta', 23),
('footer.newsletterPlaceholder', 'footer', 'Footer / Newsletter Placeholder', 'text', 'Footer / Newsletter Placeholder', 24),
('footer.solutionsItems.0', 'footer', 'Footer / Solutions Items / Item 1', 'text', 'Footer / Solutions Items / Item 1', 25),
('footer.solutionsItems.1', 'footer', 'Footer / Solutions Items / Item 2', 'text', 'Footer / Solutions Items / Item 2', 26),
('footer.solutionsItems.2', 'footer', 'Footer / Solutions Items / Item 3', 'text', 'Footer / Solutions Items / Item 3', 27),
('footer.solutionsItems.3', 'footer', 'Footer / Solutions Items / Item 4', 'text', 'Footer / Solutions Items / Item 4', 28),
('footer.solutionsTitle', 'footer', 'Footer / Solutions Title', 'text', 'Footer / Solutions Title', 29),
('hero.cta', 'hero', 'Hero / Cta', 'text', 'Hero / Cta', 30),
('hero.description', 'hero', 'Hero / Description', 'text', 'Hero / Description', 31),
('hero.subtitle', 'hero', 'Hero / Subtitle', 'text', 'Hero / Subtitle', 32),
('hero.title', 'hero', 'Hero / Title', 'text', 'Hero / Title', 33),
('map.czechRepublic', 'map', 'Map / Czech Republic', 'text', 'Map / Czech Republic', 34),
('map.slovakia', 'map', 'Map / Slovakia', 'text', 'Map / Slovakia', 35),
('navigation.blog', 'navigation', 'Navigation / Blog', 'text', 'Navigation / Blog', 36),
('navigation.contact', 'navigation', 'Navigation / Contact', 'text', 'Navigation / Contact', 37),
('navigation.countries', 'navigation', 'Navigation / Countries', 'text', 'Navigation / Countries', 38),
('navigation.home', 'navigation', 'Navigation / Home', 'text', 'Navigation / Home', 39),
('navigation.news', 'navigation', 'Navigation / News', 'text', 'Navigation / News', 40),
('navigation.services', 'navigation', 'Navigation / Services', 'text', 'Navigation / Services', 41),
('navigation.team', 'navigation', 'Navigation / Team', 'text', 'Navigation / Team', 42),
('news.subtitle', 'news', 'News / Subtitle', 'text', 'News / Subtitle', 43),
('news.title', 'news', 'News / Title', 'text', 'News / Title', 44),
('news.viewAll', 'news', 'News / View All', 'text', 'News / View All', 45),
('services.items.contracts.description', 'services', 'Services / Items / Contracts / Description', 'textarea', 'Services / Items / Contracts / Description', 46),
('services.items.contracts.title', 'services', 'Services / Items / Contracts / Title', 'text', 'Services / Items / Contracts / Title', 47),
('services.items.corporate.description', 'services', 'Services / Items / Corporate / Description', 'textarea', 'Services / Items / Corporate / Description', 48),
('services.items.corporate.title', 'services', 'Services / Items / Corporate / Title', 'text', 'Services / Items / Corporate / Title', 49),
('services.items.employment.description', 'services', 'Services / Items / Employment / Description', 'textarea', 'Services / Items / Employment / Description', 50),
('services.items.employment.title', 'services', 'Services / Items / Employment / Title', 'text', 'Services / Items / Employment / Title', 51),
('services.items.litigation.description', 'services', 'Services / Items / Litigation / Description', 'textarea', 'Services / Items / Litigation / Description', 52),
('services.items.litigation.title', 'services', 'Services / Items / Litigation / Title', 'text', 'Services / Items / Litigation / Title', 53),
('services.items.realEstate.description', 'services', 'Services / Items / Real Estate / Description', 'textarea', 'Services / Items / Real Estate / Description', 54),
('services.items.realEstate.title', 'services', 'Services / Items / Real Estate / Title', 'text', 'Services / Items / Real Estate / Title', 55),
('services.images.0', 'services', 'Services / Images / Item 1', 'image', 'Services / Images / Item 1', 56),
('services.images.1', 'services', 'Services / Images / Item 2', 'image', 'Services / Images / Item 2', 57),
('services.images.2', 'services', 'Services / Images / Item 3', 'image', 'Services / Images / Item 3', 58),
('services.images.3', 'services', 'Services / Images / Item 4', 'image', 'Services / Images / Item 4', 59),
('services.images.4', 'services', 'Services / Images / Item 5', 'image', 'Services / Images / Item 5', 60),
('services.subtitle', 'services', 'Services / Subtitle', 'textarea', 'Services / Subtitle', 61),
('services.title', 'services', 'Services / Title', 'text', 'Services / Title', 62),
('team.businessCard', 'team', 'Team / Business Card', 'text', 'Team / Business Card', 58),
('team.members.0.description', 'team', 'Team / Members / Item 1 / Description', 'textarea', 'Team / Members / Item 1 / Description', 59),
('team.members.0.name', 'team', 'Team / Members / Item 1 / Name', 'text', 'Team / Members / Item 1 / Name', 60),
('team.members.0.position', 'team', 'Team / Members / Item 1 / Position', 'text', 'Team / Members / Item 1 / Position', 61),
('team.members.1.description', 'team', 'Team / Members / Item 2 / Description', 'text', 'Team / Members / Item 2 / Description', 62),
('team.members.1.name', 'team', 'Team / Members / Item 2 / Name', 'text', 'Team / Members / Item 2 / Name', 63),
('team.members.1.position', 'team', 'Team / Members / Item 2 / Position', 'text', 'Team / Members / Item 2 / Position', 64),
('team.members.2.description', 'team', 'Team / Members / Item 3 / Description', 'text', 'Team / Members / Item 3 / Description', 65),
('team.members.2.name', 'team', 'Team / Members / Item 3 / Name', 'text', 'Team / Members / Item 3 / Name', 66),
('team.members.2.position', 'team', 'Team / Members / Item 3 / Position', 'text', 'Team / Members / Item 3 / Position', 67),
('team.members.3.description', 'team', 'Team / Members / Item 4 / Description', 'textarea', 'Team / Members / Item 4 / Description', 68),
('team.members.3.name', 'team', 'Team / Members / Item 4 / Name', 'text', 'Team / Members / Item 4 / Name', 69),
('team.members.3.position', 'team', 'Team / Members / Item 4 / Position', 'text', 'Team / Members / Item 4 / Position', 70),
('team.subtitle', 'team', 'Team / Subtitle', 'text', 'Team / Subtitle', 71),
('team.title', 'team', 'Team / Title', 'text', 'Team / Title', 72)
ON CONFLICT (key) DO UPDATE SET
  section = EXCLUDED.section,
  label = EXCLUDED.label,
  content_type = EXCLUDED.content_type,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order;
