insert into public.service_items (
  slug,
  title_sk, title_en, title_de, title_cn,
  description_sk, description_en, description_de, description_cn,
  icon,
  enabled,
  sort_order
) values
(
  'corporate',
  'Obchodné právo a obchodné spoločnosti',
  'Corporate Law and Business Companies',
  'Gesellschaftsrecht und Handelsgesellschaften',
  '公司法和商业公司',
  'Riešenie komplexných otázok obchodného práva a obchodných spoločností si vyžaduje odbornosť a precíznosť. Poskytujeme poradenstvo v oblasti zakladania spoločností, korporátneho riadenia, zmlúv, fúzií a akvizícií, ako aj pri dodržiavaní regulačných požiadaviek, aby vaše podnikanie prosperovalo v dynamickom prostredí.',
  'Solving complex issues of corporate law and business companies requires expertise and precision. We provide advice in the areas of company formation, corporate governance, contracts, mergers and acquisitions, as well as compliance with regulatory requirements, so that your business prospers in a dynamic environment.',
  'Die Lösung komplexer Fragen des Gesellschaftsrechts und der Handelsgesellschaften erfordert Expertise und Präzision. Wir bieten Beratung in den Bereichen Unternehmensgründung, Corporate Governance, Verträge, Fusionen und Übernahmen sowie bei der Einhaltung regulatorischer Anforderungen, damit Ihr Unternehmen in einem dynamischen Umfeld prosperiert.',
  '解决复杂的公司法和商业公司问题需要专业知识和精确性。我们提供公司成立、公司治理、合同、并购以及合规要求方面的咨询，以确保您的业务在充满活力的环境中蓬勃发展。',
  null,
  true,
  1
),
(
  'contracts',
  'Zmluvné právo',
  'Contract Law',
  'Vertragsrecht',
  '合同法',
  'Zmluvy sú základom úspešných obchodných vzťahov. Pripravujeme, posudzujeme a vyjednávame zmluvy prispôsobené vašim potrebám, aby sme chránili vaše záujmy a minimalizovali riziká.',
  'Contracts are the foundation of successful business relationships. We prepare, review and negotiate contracts tailored to your needs to protect your interests and minimize risks.',
  'Verträge sind die Grundlage erfolgreicher Geschäftsbeziehungen. Wir erstellen, prüfen und verhandeln Verträge, die auf Ihre Bedürfnisse zugeschnitten sind, um Ihre Interessen zu schützen und Risiken zu minimieren.',
  '合同是成功商业关系的基础。我们起草、审查和谈判根据您的需求量身定制的合同，以保护您的利益并尽量减少风险。',
  null,
  true,
  2
),
(
  'litigation',
  'Súdne spory',
  'Litigation',
  'Prozessführung',
  '诉讼',
  'Pri vzniku sporov sme vašimi spoľahlivými obhajcami. Naši skúsení právnici zastupujú vaše záujmy pred súdmi a poskytujú strategické poradenstvo a pevnú reprezentáciu s cieľom dosiahnuť čo najlepší výsledok.',
  'When disputes arise, we are your reliable advocates. Our experienced lawyers represent your interests before courts and provide strategic advice and solid representation with the goal of achieving the best possible result.',
  'Bei der Entstehung von Streitigkeiten sind wir Ihre zuverlässigen Anwälte. Unsere erfahrenen Rechtsanwälte vertreten Ihre Interessen vor Gerichten und bieten strategische Beratung und solide Vertretung mit dem Ziel, das bestmögliche Ergebnis zu erzielen.',
  '当发生争议时，我们是您可靠的辩护人。我们经验丰富的律师在法庭上代表您的利益，为您提供战略建议和坚定的代理，旨在实现最佳结果。',
  null,
  true,
  3
),
(
  'employment',
  'Pracovné právo',
  'Employment Law',
  'Arbeitsrecht',
  '劳动法',
  'Orientácia v oblasti pracovného práva si vyžaduje hlboké znalosti predpisov a osvedčených postupov. Radíme v otázkach pracovných zmlúv, vzťahov so zamestnancami, ukončenia pracovného pomeru a dodržiavania právnych predpisov, aby sme chránili vaše podnikanie a podporili pozitívne pracovné prostredie.',
  'Navigating employment law requires deep knowledge of regulations and proven practices. We advise on employment contracts, employee relations, termination of employment and compliance with legal regulations to protect your business and support a positive work environment.',
  'Die Orientierung im Arbeitsrecht erfordert tiefgreifende Kenntnisse der Vorschriften und bewährter Praktiken. Wir beraten in Fragen von Arbeitsverträgen, Mitarbeiterbeziehungen, Beendigung des Arbeitsverhältnisses und Einhaltung rechtlicher Vorschriften, um Ihr Unternehmen zu schützen und eine positive Arbeitsumgebung zu fördern.',
  '驾驭劳动法需要对法规和最佳实践有深入的了解。我们就此提供劳动合同、员工关系、终止雇佣和遵守法律法规方面的建议，以保护您的业务并支持积极的工作环境。',
  null,
  true,
  4
),
(
  'realEstate',
  'Nehnuteľnosti',
  'Real Estate',
  'Immobilien',
  '房地产',
  'Transakcie s nehnuteľnosťami si vyžadujú precízne plánovanie a právnu odbornosť. Poskytujeme komplexné právne služby pri nadobúdaní, vývoji, financovaní, prenájme a predaji nehnuteľností, aby sme zaistili ochranu vašich investícií a hladký priebeh transakcií.',
  'Real estate transactions require precise planning and legal expertise. We provide comprehensive legal services in acquisition, development, financing, leasing and sale of real estate to ensure protection of your investments and smooth transaction flow.',
  'Immobilientransaktionen erfordern präzise Planung und rechtliche Expertise. Wir bieten umfassende Rechtsdienstleistungen bei Erwerb, Entwicklung, Finanzierung, Vermietung und Verkauf von Immobilien, um den Schutz Ihrer Investitionen und einen reibungslosen Transaktionsablauf zu gewährleisten.',
  '房地产交易需要精确的规划和法律专业知识。我们提供房地产收购、开发、融资、租赁和销售方面的全面法律服务，以确保您的投资受到保护并确保交易顺畅进行。',
  null,
  true,
  5
)
on conflict (slug) do update set
  title_sk = excluded.title_sk,
  title_en = excluded.title_en,
  title_de = excluded.title_de,
  title_cn = excluded.title_cn,
  description_sk = excluded.description_sk,
  description_en = excluded.description_en,
  description_de = excluded.description_de,
  description_cn = excluded.description_cn,
  icon = excluded.icon,
  enabled = excluded.enabled,
  sort_order = excluded.sort_order,
  updated_at = now();
